filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - "/logs/*"

processors:
  - decode_json_fields:
      fields: ["message"]
      target: ""

output.logstash:
  hosts: "logstash:5044"

logging.metrics.enabled: false
