spring:
  application.name: Explore With Me (Stats)
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm_stats
    username: stats
    password: stats
  jpa:
    hibernate.ddl-auto: none
    open-in-view: false
  sql.init.mode: always
logging.level:
  org.zalando.logbook: TRACE
server.port: 9090