spring:
  main.banner-mode: OFF
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ewm_stats
    username: stats
    password: stats
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging.level:
  ru.practicum.ewm: DEBUG
  org.hibernate.orm.jdbc.bind: TRACE
